apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: tcc/front
          imagePullPolicy: Never
          resources:
            limits:
              cpu: '250m'
              memory: '1G'
          env:
            - name: REACT_APP_MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: REACT_APP_MAPBOX_TOKEN
---
apiVersion: v1
kind: Service
metadata:
  name: front-srv
spec:
  selector:
    app: front
  type: ClusterIP
  ports:
    - name: front
      protocol: TCP
      port: 3000
      targetPort: 3000
