apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tcc/backend
          imagePullPolicy: Never
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_URL
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: backend-srv
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 3000
      targetPort: 3000
